// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: gopay_app.proto

/* eslint-disable */
import type {
  Account,
  AccountActionCatalog,
} from "@byte-v-forge/common-ui/proto/byte/v/forge/contracts/account/v1/account";

export const protobufPackage = "gopay_app";

export enum GoPayOTPChannel {
  GOPAY_OTP_CHANNEL_UNSPECIFIED = "GOPAY_OTP_CHANNEL_UNSPECIFIED",
  GOPAY_OTP_CHANNEL_SMS = "GOPAY_OTP_CHANNEL_SMS",
  GOPAY_OTP_CHANNEL_WHATSAPP = "GOPAY_OTP_CHANNEL_WHATSAPP",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum GoPayAccountWorkflowOperation {
  GOPAY_ACCOUNT_WORKFLOW_OPERATION_UNSPECIFIED = "GOPAY_ACCOUNT_WORKFLOW_OPERATION_UNSPECIFIED",
  GOPAY_ACCOUNT_WORKFLOW_OPERATION_LOGIN = "GOPAY_ACCOUNT_WORKFLOW_OPERATION_LOGIN",
  GOPAY_ACCOUNT_WORKFLOW_OPERATION_SIGNUP = "GOPAY_ACCOUNT_WORKFLOW_OPERATION_SIGNUP",
  GOPAY_ACCOUNT_WORKFLOW_OPERATION_ENSURE_PIN_SETUP = "GOPAY_ACCOUNT_WORKFLOW_OPERATION_ENSURE_PIN_SETUP",
  GOPAY_ACCOUNT_WORKFLOW_OPERATION_CHECK_BALANCE = "GOPAY_ACCOUNT_WORKFLOW_OPERATION_CHECK_BALANCE",
  GOPAY_ACCOUNT_WORKFLOW_OPERATION_CHECK_PIN = "GOPAY_ACCOUNT_WORKFLOW_OPERATION_CHECK_PIN",
  GOPAY_ACCOUNT_WORKFLOW_OPERATION_CHANGE_PHONE = "GOPAY_ACCOUNT_WORKFLOW_OPERATION_CHANGE_PHONE",
  GOPAY_ACCOUNT_WORKFLOW_OPERATION_PROVISION = "GOPAY_ACCOUNT_WORKFLOW_OPERATION_PROVISION",
  GOPAY_ACCOUNT_WORKFLOW_OPERATION_DEACTIVATE = "GOPAY_ACCOUNT_WORKFLOW_OPERATION_DEACTIVATE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface GoPayOTPChannelDescriptor {
  channel: GoPayOTPChannel;
  /** 稳定请求/投影值：sms、wa */
  api_value: string;
  /** GoPay verification_method：otp_sms、otp_wa */
  provider_method: string;
  aliases: string[];
  requires_sms_activation: boolean;
}

export interface GoPayAccountWorkflowRequest {
  gopay_account_id: string;
  operation: GoPayAccountWorkflowOperation;
  phone: string;
  country_code: string;
  pin: string;
  otp_channel: string;
}

export interface GoPayAccountWorkflowResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}

export interface GetGopayActionCatalogRequest {
}

export interface GetGopayActionCatalogResponse {
  success: boolean;
  error_message: string;
  catalog: AccountActionCatalog | undefined;
}

export interface ChangePhoneStartRequest {
  pin: string;
  /** 编排服务从接码服务取号后传入，不含国家码 */
  new_phone: string;
  /** 电话区号，例如 "+62" */
  country_code: string;
  state_json: string;
}

export interface ChangePhoneStartResponse {
  success: boolean;
  error_message: string;
  /** 实际获取到的号码 */
  new_phone: string;
  /** 保留字段；activation_id 由编排服务传递给接码服务 */
  activation_id: string;
  otp_sent: boolean;
  state_json: string;
}

export interface ChangePhoneCompleteRequest {
  otp: string;
  state_json: string;
}

export interface ChangePhoneCompleteResponse {
  success: boolean;
  error_message: string;
  state_json: string;
}

export interface ChangePhoneRetryRequest {
  state_json: string;
}

export interface ChangePhoneRetryResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  state_json: string;
}

export interface DeactivateStartRequest {
  pin: string;
  state_json: string;
}

export interface DeactivateStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  state_json: string;
}

export interface DeactivateCompleteRequest {
  otp: string;
  state_json: string;
}

export interface DeactivateCompleteResponse {
  success: boolean;
  error_message: string;
  deactivated_at: number;
  state_json: string;
}

export interface LoginStartRequest {
  /** 登录手机号；必填，由上游编排传入 */
  phone: string;
  /** 电话区号，例如 "+62"；必填，由上游编排传入 */
  country_code: string;
  /** 登录 PIN；必填，由上游编排传入 */
  pin: string;
  /** sms 或 wa；为空时由 provider 选择当前流程默认通道 */
  otp_channel: string;
  state_json: string;
}

export interface LoginStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  state_json: string;
}

export interface LoginCompleteRequest {
  otp: string;
  state_json: string;
}

export interface LoginCompleteResponse {
  success: boolean;
  error_message: string;
  phone: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  state_json: string;
}

export interface SignupStartRequest {
  /** 新账号手机号；必填，由上游编排传入 */
  phone: string;
  name: string;
  email: string;
  /** 电话区号，例如 "+62"；为空时 provider 使用 GoPay 默认国家区号 */
  country_code: string;
  /** sms 或 wa；为空默认 sms；由服务映射为 otp_sms / otp_wa */
  otp_channel: string;
  /** 直接进入 signup methods，不预探测手机号是否已注册 */
  skip_phone_probe: boolean;
  state_json: string;
}

export interface SignupStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  /** 上游原始响应 JSON */
  raw_json: string;
  retry_timer_seconds: number[];
  state_json: string;
}

export interface SignupRetryRequest {
  state_json: string;
}

export interface SignupRetryResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  /** 上游原始响应 JSON */
  raw_json: string;
  state_json: string;
}

export interface SignupCompleteRequest {
  otp: string;
  state_json: string;
}

export interface SignupCompleteResponse {
  success: boolean;
  error_message: string;
  phone: string;
  pin_setup_required: boolean;
  /** 上游原始响应 JSON */
  raw_json: string;
  state_json: string;
}

export interface GenerateDeviceProxyRequest {
  account_id: string;
  country_code: string;
  force_new: boolean;
  skip_preflight: boolean;
  ephemeral_profile: boolean;
}

export interface GenerateDeviceProxyResponse {
  success: boolean;
  error_message: string;
  proxy_slot: number;
  dynamic_egress_size: number;
  proxy_hash: string;
  device_fingerprint: string;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface CreatePinStartRequest {
  pin: string;
  /** sms 或 wa；为空默认 sms；由服务映射为 otp_sms / otp_wa */
  otp_channel: string;
  state_json: string;
}

export interface CreatePinStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  state_json: string;
}

export interface CreatePinRetryRequest {
  state_json: string;
}

export interface CreatePinRetryResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  state_json: string;
}

export interface CreatePinCompleteRequest {
  otp: string;
  pin: string;
  state_json: string;
}

export interface CreatePinCompleteResponse {
  success: boolean;
  error_message: string;
  phone: string;
  pin_setup_complete: boolean;
  state_json: string;
}

export interface AuthStartRequest {
  /** 手机号；必填，由上游编排传入 */
  phone: string;
  /** 电话区号，例如 "+62"；为空时 provider 使用 GoPay 默认国家区号 */
  country_code: string;
  /** login 使用；需要 PIN 的步骤必须由调用方传入 */
  pin: string;
  /** sms 或 wa；为空时由 provider 选择当前流程默认通道 */
  otp_channel: string;
  state_json: string;
}

export interface AuthStartResponse {
  success: boolean;
  error_message: string;
  /** token 或 login；注册走 SignupStart */
  mode: string;
  stage: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  ready: boolean;
  pin_setup_required: boolean;
  state_json: string;
}

export interface AuthCompleteRequest {
  otp: string;
  /** 保留给需要 PIN 的登录后置步骤；需要 PIN 的步骤必须由调用方传入 */
  pin: string;
  state_json: string;
}

export interface AuthCompleteResponse {
  success: boolean;
  error_message: string;
  /** token 或 login；注册走 SignupStart */
  mode: string;
  stage: string;
  phone: string;
  ready: boolean;
  pin_setup_required: boolean;
  pin_setup_complete: boolean;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  state_json: string;
}

export interface CheckTokenValidRequest {
  state_json: string;
}

export interface CheckTokenValidResponse {
  success: boolean;
  error_message: string;
  stage: string;
  phone: string;
  token_valid: boolean;
  refreshed: boolean;
  balance_amount: number;
  has_min_balance: boolean;
  balance_currency: string;
  state_json: string;
}

export interface ClaimEnvelopeRequest {
  /** 为空时从 link 提取 */
  envelope_request_id: string;
  /** app.gopay 短链、gopay:// deeplink 或 customer API URL */
  link: string;
  state_json: string;
}

export interface ClaimEnvelopeResponse {
  success: boolean;
  error_message: string;
  /** 实际请求路径里的 id */
  envelope_request_id: string;
  /** 返回 data.envelope_request_id；可能与路径 id 不同 */
  response_envelope_request_id: string;
  status: string;
  http_status: number;
  raw_json: string;
  state_json: string;
}

export interface UnlinkRequest {
  state_json: string;
}

export interface UnlinkResponse {
  success: boolean;
  error_message: string;
  unlinked_count: number;
  state_json: string;
}

export interface StatusRequest {
  state_json: string;
}

export interface StatusResponse {
  stage: string;
  phone: string;
  /** 当前设备指纹摘要 */
  device_fingerprint: string;
  deactivated_at: number;
  error_message: string;
  token_present: boolean;
  login_otp_sent_at_unix: number;
  login_otp_expires_at_unix: number;
  signup_otp_sent_at_unix: number;
  signup_otp_expires_at_unix: number;
  signup_pin_otp_sent_at_unix: number;
  signup_pin_otp_expires_at_unix: number;
  balance_amount: number;
  has_min_balance: boolean;
  balance_currency: string;
  pin_setup: boolean;
  pin_setup_at_unix: number;
  state_json: string;
}

export interface GetReadyAccountTokenRequest {
  state_json: string;
}

export interface GetReadyAccountTokenResponse {
  success: boolean;
  error_message: string;
  account_token: string;
  phone: string;
  state_json: string;
}

export interface CheckDeactivationRequest {
  state_json: string;
}

export interface CheckDeactivationResponse {
  completed: boolean;
  remaining_seconds: number;
  state_json: string;
}

export interface GetQrIdRequest {
  state_json: string;
}

export interface GetQrIdResponse {
  success: boolean;
  error_message: string;
  qr_id: string;
  state_json: string;
}

export interface CheckPhoneRequest {
  /** 不含国家码 */
  phone: string;
  /** 电话区号，例如 "+62"；为空时 provider 使用 GoPay 默认国家区号 */
  country_code: string;
  /** 必须来自 GenerateDeviceProxy；CheckPhone 不隐式生成设备或代理 */
  state_json: string;
}

export interface CheckPhoneResponse {
  /** true=未注册，可用于接收改号 */
  available: boolean;
  error_message: string;
  /** available / registered / rate_limited / error */
  status: string;
  proxy_slot: number;
  dynamic_egress_size: number;
  proxy_hash: string;
  device_fingerprint: string;
  /** 原样返回输入链路态；用于后续注册复用同一 proxy/device */
  state_json: string;
}

export interface GopayAccount {
  account: Account | undefined;
  phone: string;
  country_code: string;
  balance_amount: number;
  balance_currency: string;
  /** sms / wa，由注册/登录使用的账户通道沉淀 */
  otp_channel: string;
}

export interface GetGopayAccountRequest {
  gopay_account_id: string;
}

export interface GetGopayAccountResponse {
  success: boolean;
  error_message: string;
  account: GopayAccount | undefined;
}

export interface ListGopayAccountsRequest {
  limit: number;
  cursor: string;
}

export interface ListGopayAccountsResponse {
  success: boolean;
  error_message: string;
  accounts: GopayAccount[];
  next_cursor: string;
}

export interface LoadGopayAccountStateRequest {
  gopay_account_id: string;
}

export interface LoadGopayAccountStateResponse {
  success: boolean;
  error_message: string;
  account:
    | GopayAccount
    | undefined;
  /** Sensitive raw runtime state. Only trusted orchestration callers should request it. */
  state_json: string;
}

export interface SaveGopayAccountStateRequest {
  gopay_account_id: string;
  /** Sensitive raw runtime state owned by gopay-app. */
  state_json: string;
}

export interface SaveGopayAccountStateResponse {
  success: boolean;
  error_message: string;
  account: GopayAccount | undefined;
}

export interface DeleteGopayAccountRequest {
  gopay_account_id: string;
}

export interface DeleteGopayAccountResponse {
  success: boolean;
  error_message: string;
}

export interface GetGopayAccountProfileRequest {
  gopay_account_id: string;
}

export interface GetGopayAccountProfileResponse {
  success: boolean;
  error_message: string;
  gopay_account_id: string;
  wa_phone: string;
  country_code: string;
  updated_at_unix: number;
  otp_channel: string;
  pin_configured: boolean;
}

export interface SaveGopayAccountProfileRequest {
  gopay_account_id: string;
  wa_phone: string;
  country_code: string;
  otp_channel: string;
  /** 仅写入；响应不返回 PIN */
  pin: string;
}

export interface SaveGopayAccountProfileResponse {
  success: boolean;
  error_message: string;
  gopay_account_id: string;
  wa_phone: string;
  country_code: string;
  updated_at_unix: number;
  otp_channel: string;
  pin_configured: boolean;
}

export interface StartGopayPaymentRequest {
  snap_token: string;
  checkout_url: string;
  checkout_session_id: string;
  /** true / false / qris */
  tokenization: string;
  /** GoPayAccount state owner; gopay-app resolves phone/country/otp_channel/PIN internally. */
  gopay_account_id: string;
  /** 订单应付金额；用于余额充足性检查，单位按 currency 最小单位 */
  amount: number;
  currency: string;
}

export interface StartGopayPaymentResponse {
  success: boolean;
  error_message: string;
  flow_id: string;
  snap_token: string;
  issued_after_unix: number;
  expires_at_unix: number;
  checkout_url: string;
  checkout_session_id: string;
  otp_required: boolean;
  otp_channel: string;
  gopay_account_id: string;
  amount: number;
  currency: string;
  otp_target: string;
}

export interface CompleteGopayPaymentRequest {
  flow_id: string;
  otp: string;
}

export interface ResendGopayPaymentOTPRequest {
  flow_id: string;
}

export interface ResendGopayPaymentOTPResponse {
  success: boolean;
  error_message: string;
  flow_id: string;
  issued_after_unix: number;
}

export interface ConfirmGopayPaymentRequest {
  flow_id: string;
}

export interface CancelGopayPaymentRequest {
  flow_id: string;
}

export interface CancelGopayPaymentResponse {
  success: boolean;
  error_message: string;
}

export interface GopayPaymentResponse {
  success: boolean;
  error_message: string;
  charge_ref: string;
  snap_token: string;
  awaiting_manual_confirmation: boolean;
  deeplink_url: string;
  qr_code_url: string;
  finish_redirect_url: string;
  finish_200_redirect_url: string;
  qr_string: string;
}
