// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: gpt_account.proto

/* eslint-disable */
import type { Account as Account1 } from "@byte-v-forge/common-ui/proto/byte/v/forge/contracts/account/v1/account";

export const protobufPackage = "gpt_account";

export interface Account {
  charge_ref: string;
  plus_trial_eligible?: boolean | undefined;
  plus_active?: boolean | undefined;
  tier: string;
  activation_channel?: string | undefined;
  primary_mailbox_email: string;
  account: Account1 | undefined;
}

export interface AccountCredential {
  /** Sensitive. Only gpt-account should persist it; Account projections must not carry it. */
  password: string;
}

export interface CreateAccountRequest {
  account: Account | undefined;
  credential: AccountCredential | undefined;
}

export interface CreateAccountResponse {
  account: Account | undefined;
}

export interface GetAccountRequest {
  account_id: string;
}

export interface GetAccountResponse {
  account: Account | undefined;
}

export interface UpdateAccountRequest {
  account: Account | undefined;
  credential: AccountCredential | undefined;
}

export interface UpdateAccountResponse {
  account: Account | undefined;
}

export interface GetAccountCredentialRequest {
  account_id: string;
}

export interface GetAccountCredentialResponse {
  account_id: string;
  credential: AccountCredential | undefined;
}

export interface DeleteAccountRequest {
  account_id: string;
}

export interface DeleteAccountResponse {
  ack: boolean;
}

export interface ListAccountsRequest {
  status: string;
  limit: number;
  email: string;
  cursor: string;
}

export interface ListAccountsResponse {
  accounts: Account[];
  next_cursor: string;
}

export interface GPTEmailAllocation {
  email: string;
  primary_email: string;
  is_primary: boolean;
  status: string;
  splittable: boolean;
  assigned_account_id: string;
  last_error: string;
  created_at: number;
  updated_at: number;
}

export interface UpsertGPTEmailAllocationRequest {
  allocation: GPTEmailAllocation | undefined;
}

export interface UpsertGPTEmailAllocationResponse {
  allocation: GPTEmailAllocation | undefined;
}

export interface ListGPTEmailAllocationsRequest {
  status: string;
  limit: number;
  primary_email: string;
  splittable_only: boolean;
  cursor: string;
  is_primary?: boolean | undefined;
  email: string;
}

export interface ListGPTEmailAllocationsResponse {
  allocations: GPTEmailAllocation[];
  next_cursor: string;
}

export interface ClaimGPTEmailAllocationRequest {
  email: string;
  account_id: string;
  expected_status: string;
  status: string;
  require_primary_splittable: boolean;
  expected_primary_status: string;
}

export interface ClaimGPTEmailAllocationResponse {
  claimed: boolean;
  allocation: GPTEmailAllocation | undefined;
}

export interface CreateGPTEmailAliasAllocationRequest {
  primary_email: string;
  account_id: string;
}

export interface CreateGPTEmailAliasAllocationResponse {
  created: boolean;
  allocation: GPTEmailAllocation | undefined;
}

export interface MarkGPTEmailAllocationStatusRequest {
  email: string;
  status: string;
  last_error: string;
}

export interface MarkGPTEmailAllocationStatusResponse {
  allocation: GPTEmailAllocation | undefined;
}
