// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_n8n.proto

/* eslint-disable */
import type {
  AcquireProxyLeaseRequest,
  ProxyChainPlan,
  ProxyDynamicLease,
  ProxyEdgeAccessCheck,
  ProxyExitGeo,
  ProxyIPFraudCheck,
  ProxyTargetConnectivityCheck,
} from "./byte/v/forge/contracts/proxyruntime/v1/proxy_runtime";
import type {
  ActivityCodexOAuthStepData,
  ActivityProbePlusTrialStepData,
  ActivityProbeTierStepData,
} from "./orchestrator_activity_data";

export const protobufPackage = "orchestrator";

export interface N8NWorkflowTriggerPayload {
  job_id: string;
  account_id: string;
  account_ids: string[];
  label: string;
  max_reuse_count: number;
}

export interface N8NActionCompleteResult {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  action: string;
  started: boolean;
  success: boolean;
  error_message: string;
  result: N8NActionCompleteData | undefined;
}

export interface N8NActionCompleteData {
  auth_finish: N8NAuthFinishData | undefined;
  auth_failure: N8NAuthFailureData | undefined;
  codex_oauth: ActivityCodexOAuthStepData | undefined;
  codex_oauth_batch: N8NCodexOAuthBatchCompleteData | undefined;
  probe_complete: N8NProbeCompleteData | undefined;
  probe_token: N8NProbeTokenData | undefined;
}

export interface N8NActionStepData {
  probe_token: N8NProbeTokenData | undefined;
  probe_plus_trial: ActivityProbePlusTrialStepData | undefined;
  probe_tier: ActivityProbeTierStepData | undefined;
}

export interface N8NActionStepResult {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  step: string;
  success: boolean;
  data: N8NActionStepData | undefined;
}

export interface N8NActionSuccessResult {
  success: boolean;
  job_id: string;
  parent_job_id: string;
  account_id: string;
  activation_id: string;
  label: string;
  max_reuse_count: number;
  n8n_execution_id: string;
}

export interface N8NAuthStepResult {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  step: string;
  flow_id: string;
  email: string;
  channel: string;
  target: string;
  otp_required: boolean;
  otp_found: boolean;
  otp_issued_after_unix: number;
  otp_timeout_seconds: number;
  otp_source: string;
  message_id: string;
  result_ready: boolean;
  result_ref: string;
  waiting: boolean;
  success: boolean;
  result_secret_error: string;
}

export interface N8NAuthFinishData {
  account_id: string;
  n8n_execution_id: string;
  driver: string;
  mode: string;
  session_token_present: boolean;
  access_token_present: boolean;
  plus_trial_checked?: boolean | undefined;
  plus_trial_eligible?: boolean | undefined;
}

export interface N8NAuthFailureData {
  account_id: string;
  n8n_execution_id: string;
  flow_id: string;
  reason: string;
  error_message: string;
  stage: string;
  mode: string;
}

export interface N8NAuthEdgeData {
  account_id: string;
  n8n_execution_id: string;
  auth_edge_check_target: string;
  auth_edge_accepted?: boolean | undefined;
  error_message: string;
  access_token_cached?: boolean | undefined;
  access_token_expires_at_unix: number;
  access_token_ttl_seconds: number;
  driver: string;
  mode: string;
  chatgpt_csrf_status: number;
  chatgpt_csrf_attempt: number;
  chatgpt_csrf_edge_challenge?: boolean | undefined;
  chatgpt_csrf_ready?: boolean | undefined;
}

export interface N8NDynamicProxyResult {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  step: string;
  success: boolean;
  proxy_url: string;
  preflight_data: N8NDynamicProxyPreflightData | undefined;
  auth_edge_data: N8NAuthEdgeData | undefined;
}

export interface N8NChannelOTPWaitResult {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  flow_id: string;
  action: string;
  operation: string;
  step: string;
  channel: string;
  target: string;
  otp_required: boolean;
  otp_found: boolean;
  otp_source: string;
  otp_issued_after_unix: number;
  otp_timeout_seconds: number;
  message_id: string;
  waiting: boolean;
  success: boolean;
  data: N8NChannelOTPWaitData | undefined;
}

export interface N8NChannelOTPResumePayload {
  job_id: string;
  account_id: string;
  operation: string;
  flow_id: string;
  channel: string;
  target: string;
  otp_source: string;
  otp_issued_after_unix: number;
  n8n_execution_id: string;
  message_id: string;
}

export interface N8NChannelOTPMetadata {
  message_id: string;
  provider_key: string;
  manual_otp_submitted: boolean;
}

export interface N8NChannelOTPWaitDetail {
  action: string;
  operation: string;
  account_id: string;
  flow_id: string;
  channel: string;
  target: string;
  timeout_seconds: number;
  otp_issued_after_unix: number;
  resume_url_registered: boolean;
  n8n_execution_id: string;
  wait_index: string;
  mailbox_poll_requested: boolean;
}

export interface N8NChannelOTPCompleteData {
  channel: string;
  target: string;
  found: boolean;
  source: string;
  timeout_seconds: number;
  issued_after_unix: number;
  received_at_unix: number;
  n8n_execution_id: string;
  resume_event_received: boolean;
  account_id: string;
  flow_id: string;
  message_id: string;
  provider_key: string;
  manual_otp_submitted: boolean;
}

export interface N8NChannelOTPWaitData {
  detail: N8NChannelOTPWaitDetail | undefined;
  complete: N8NChannelOTPCompleteData | undefined;
}

export interface N8NDynamicProxySettings {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  purpose: string;
  country_code: string;
  region: string;
  state: string;
  geo_source: string;
  preflight_enabled: boolean;
  require_residential: boolean;
  min_ip_purity_score: number;
  cf_canary_enabled: boolean;
  max_proxy_attempts: number;
  target_connectivity_urls: string[];
  auth_edge_check_enabled: boolean;
  auth_edge_check_target: string;
  lease_request: AcquireProxyLeaseRequest | undefined;
}

export interface N8NDynamicProxyPreflightDetail {
  account_id: string;
  n8n_execution_id: string;
  purpose: string;
  geo_source: string;
  country_code: string;
  region: string;
  max_proxy_attempts: number;
  target_connectivity_urls: string[];
  proxy_preflight_step: string;
  preflight_enabled: boolean;
  cf_canary_enabled: boolean;
  require_residential: boolean;
  min_ip_purity_score: number;
  auth_edge_check_enabled: boolean;
  auth_edge_check_target: string;
}

export interface N8NDynamicProxyGeoData {
  account_id: string;
  n8n_execution_id: string;
  country_code: string;
  region: string;
  geo_source: string;
}

export interface N8NDynamicProxyPreflightData {
  account_id: string;
  n8n_execution_id: string;
  purpose: string;
  attempt: number;
  max_proxy_attempts: number;
  accepted: boolean;
  success: boolean;
  reason: string;
  error_message: string;
  preflight_enabled: boolean;
  cf_canary_enabled: boolean;
  require_residential: boolean;
  min_ip_purity_score: number;
  proxy_session_hash: string;
  exit_ip: string;
  exit_geo: ProxyExitGeo | undefined;
  ip_fraud_check: ProxyIPFraudCheck | undefined;
  edge_access_check: ProxyEdgeAccessCheck | undefined;
  proxy_runtime_lease: ProxyDynamicLease | undefined;
  chain_plan: ProxyChainPlan | undefined;
  target_connectivity_check: ProxyTargetConnectivityCheck | undefined;
  target_connectivity_enabled: boolean;
  target_connectivity_reachable: boolean;
}

export interface N8NAuthStepRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  flow_id: string;
  email: string;
  proxy_url: string;
}

export interface N8NAuthOTPWaitRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  flow_id: string;
  channel: string;
  target: string;
  timeout_seconds: number;
  otp_issued_after_unix: number;
  resume_url: string;
}

export interface N8NAuthCompleteRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  flow_id: string;
  otp_source: string;
  otp_issued_after_unix: number;
}

export interface N8NAuthFinishRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  result_ref: string;
}

export interface N8NAuthFailRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  flow_id: string;
  error_message: string;
  data: N8NAuthFailureData | undefined;
}

export interface N8NDynamicProxyRecordRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  proxy_url: string;
  data: N8NDynamicProxyPreflightData | undefined;
}

export interface N8NDynamicProxyCheckRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  proxy_url: string;
  data: N8NDynamicProxyPreflightData | undefined;
}

export interface N8NDynamicProxyFailRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  error_message: string;
  data: N8NDynamicProxyPreflightData | undefined;
}

export interface N8NCodexOAuthBindRequest {
  job_id: string;
  n8n_execution_id: string;
}

export interface N8NCodexOAuthCompleteRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  auth_secret_key: string;
  driver: string;
  add_phone_confirmed?: boolean | undefined;
  data: ActivityCodexOAuthStepData | undefined;
}

export interface N8NCodexOAuthFailRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  step: string;
  error_message: string;
  data: ActivityCodexOAuthStepData | undefined;
}

export interface N8NCodexOAuthBatchChildRequest {
  parent_job_id: string;
  account_id: string;
  label: string;
  max_reuse_count: number;
  n8n_execution_id: string;
}

export interface N8NCodexOAuthBatchCompleteRequest {
  job_id: string;
  n8n_execution_id: string;
  total_count: number;
  mode: string;
}

export interface N8NCodexOAuthBatchCompleteData {
  n8n_execution_id: string;
  total_count: number;
  mode: string;
}

export interface N8NProbeAccountFacts {
  account_id: string;
  plus_trial_known: boolean;
  plus_trial_eligible: boolean;
  tier: string;
  plus_active: boolean;
}

export interface N8NProbeTokenData {
  account_id: string;
  n8n_execution_id: string;
  proxy_url: string;
  account: N8NProbeAccountFacts | undefined;
  token_valid?: boolean | undefined;
  access_token_cached?: boolean | undefined;
  requires_login?: boolean | undefined;
  expires_at_unix: number;
  ttl_seconds: number;
  reason: string;
}

export interface N8NProbeCompleteRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  plus_trial: ActivityProbePlusTrialStepData | undefined;
  tier: ActivityProbeTierStepData | undefined;
}

export interface N8NProbeCompleteData {
  account_id: string;
  n8n_execution_id: string;
  probe_plus_trial: ActivityProbePlusTrialStepData | undefined;
  probe_tier: ActivityProbeTierStepData | undefined;
  account_updated?: boolean | undefined;
  account_update_error: string;
}

export interface N8NProbeFailRequest {
  job_id: string;
  account_id: string;
  n8n_execution_id: string;
  step: string;
  error_message: string;
  data: N8NProbeTokenData | undefined;
}
