// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_gopay_payment_activity.proto

/* eslint-disable */

export const protobufPackage = "orchestrator";

export interface GoPayActivityInput {
  job_id: string;
  account_id: string;
  session_token: string;
  access_token: string;
  use_account_token: boolean;
  tokenization: string;
  checkout_url: string;
  checkout_session_id: string;
  /** sms 时 payment 触发 resend-otp；wa/空值不触发 */
  otp_channel: string;
  state_json: string;
  prepared_flow_id: string;
  gopay_phone: string;
  sms_activation_id: string;
  /** GoPayAccount state owner and OTP target. */
  gopay_account_id: string;
  /** 已有 GoPay state 直接支付时跳过余额等待 */
  skip_account_balance_check: boolean;
  /** GoPay PIN；需要 PIN 的步骤必须由调用方显式传入 */
  pin: string;
  /** 电话区号；需要链接 GoPay 的步骤必须由调用方显式传入 */
  country_code: string;
  /** workflow 前置动态代理；仅运行时透传，不持久化 */
  proxy_url: string;
}

export interface GoPayPaymentPrepareOutput {
  flow_id: string;
  snap_token: string;
  checkout_url: string;
  checkout_session_id: string;
  use_account_token: boolean;
  data: { [key: string]: any } | undefined;
  state_json: string;
  retryable_fresh_checkout: boolean;
  checkout_attempt: number;
  stage: string;
}
