// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_gopay_app.proto

/* eslint-disable */
import type { StatusResponse } from "./gopay_app";

export const protobufPackage = "orchestrator";

export interface EnsureLogonRequest {
  job_id: string;
  account_id: string;
  gopay_account_id: string;
}

export interface EnsureLogonResponse {
  ready: boolean;
  stage: string;
  phone: string;
  status_before: StatusResponse | undefined;
  status_after: StatusResponse | undefined;
  already_ready: boolean;
  change_phone_complete: boolean;
  deactivate_complete: boolean;
  logon_complete: boolean;
  account_token_ready: boolean;
  error_message: string;
  signup_complete: boolean;
  signup_pin_complete: boolean;
}

export interface GoPayAppRequest {
  phone: string;
  country_code: string;
  pin: string;
  otp_channel: string;
  gopay_account_id: string;
  /** login/signup/create_pin/check_balance/check_pin/change_phone/provision */
  operation: string;
}

export interface GoPayAppResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}

export interface GoPayPaymentRequest {
  account_id: string;
  source_job_id: string;
  /** GoPayAccount state owner; otp_channel/PIN/phone are resolved by gopay-app. */
  gopay_account_id: string;
  /** true / false / qris */
  tokenization: string;
}

export interface GoPayWAPaymentRequest {
  account_id?: string | undefined;
  access_token?: string | undefined;
  source_job_id: string;
  /** GoPayAccount state owner and OTP target. */
  gopay_account_id: string;
  /** WA 支付手机号；调用方必须显式传入 */
  wa_phone: string;
  /** GoPay PIN；需要 PIN 的步骤必须由调用方显式传入 */
  pin: string;
  /** 电话区号，例如 "+62"；为空时 provider 使用 GoPay 默认国家区号 */
  country_code: string;
}

export interface GoPayQRISPaymentActivateRequest {
  account_id: string;
  source_job_id: string;
  gopay_account_id: string;
}

export interface GoPayPaymentResponse {
  job_id: string;
  started: boolean;
  success: boolean;
  error_message: string;
  charge_ref: string;
  snap_token: string;
  activation_id: string;
  phone: string;
  wa_phone: string;
  bound_phone: string;
  change_phone_activation_id: string;
  change_phone_complete: boolean;
  gopay_account_id: string;
}

export interface GoPayPaymentRebindRequest {
  source_job_id: string;
  account_id: string;
  gopay_account_id: string;
  pin: string;
  country_code: string;
}

export interface ConfirmManualGoPayPaymentRequest {
  job_id: string;
}

export interface ConfirmManualGoPayPaymentResponse {
  success: boolean;
  job_id: string;
  error_message: string;
}

export interface GoPayAccountStatusRequest {
  gopay_account_id: string;
}

export interface GoPayAccountStatusResponse {
  success: boolean;
  error_message: string;
  status: StatusResponse | undefined;
}

export interface GoPayAccountClearStateRequest {
  gopay_account_id: string;
}

export interface GoPayAccountClearStateResponse {
  success: boolean;
  error_message: string;
}

export interface GoPayAccountSetWAPhoneRequest {
  gopay_account_id: string;
  wa_phone: string;
}

export interface GoPayAccountGetWAPhoneRequest {
  gopay_account_id: string;
}

export interface GoPayAccountWAPhoneResponse {
  success: boolean;
  error_message: string;
  gopay_account_id: string;
  wa_phone: string;
}

export interface GoPayAccountCheckPhoneRequest {
  gopay_account_id: string;
  phone: string;
  country_code: string;
}

export interface GoPayAccountCheckPhoneResponse {
  success: boolean;
  error_message: string;
  available: boolean;
  status: string;
}

export interface GoPayAccountCheckBalanceRequest {
  gopay_account_id: string;
}

export interface GoPayAccountCheckBalanceResponse {
  success: boolean;
  error_message: string;
  stage: string;
  phone: string;
  token_valid: boolean;
  refreshed: boolean;
  balance_amount: number;
  has_min_balance: boolean;
  balance_currency: string;
}

export interface GoPayAccountAuthStartRequest {
  gopay_account_id: string;
  phone: string;
  country_code: string;
  pin: string;
  /** sms 或 wa；为空时由 provider 选择当前流程默认通道 */
  otp_channel: string;
}

export interface GoPayAccountAuthStartResponse {
  success: boolean;
  error_message: string;
  mode: string;
  stage: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  ready: boolean;
  pin_setup_required: boolean;
}

export interface GoPayAccountAuthCompleteRequest {
  gopay_account_id: string;
  otp: string;
  pin: string;
}

export interface GoPayAccountAuthCompleteResponse {
  success: boolean;
  error_message: string;
  mode: string;
  stage: string;
  phone: string;
  ready: boolean;
  pin_setup_required: boolean;
  pin_setup_complete: boolean;
}

export interface GoPayAccountChangePhoneStartRequest {
  gopay_account_id: string;
  new_phone: string;
  pin: string;
  country_code: string;
}

export interface GoPayAccountChangePhoneStartResponse {
  success: boolean;
  error_message: string;
  new_phone: string;
  otp_sent: boolean;
}

export interface GoPayAccountChangePhoneCompleteRequest {
  gopay_account_id: string;
  otp: string;
}

export interface GoPayAccountChangePhoneCompleteResponse {
  success: boolean;
  error_message: string;
}

export interface GoPayAccountChangePhoneRetryRequest {
  gopay_account_id: string;
}

export interface GoPayAccountChangePhoneRetryResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
}

export interface GoPayAccountSignupStartRequest {
  gopay_account_id: string;
  phone: string;
  name: string;
  email: string;
  country_code: string;
  /** sms 或 wa；为空默认 sms */
  otp_channel: string;
}

export interface GoPayAccountSignupStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
}

export interface GoPayAccountSignupCompleteRequest {
  gopay_account_id: string;
  otp: string;
}

export interface GoPayAccountSignupCompleteResponse {
  success: boolean;
  error_message: string;
  phone: string;
  pin_setup_required: boolean;
}

export interface GoPayAccountCreatePinStartRequest {
  gopay_account_id: string;
  pin: string;
  /** sms 或 wa；为空默认 sms */
  otp_channel: string;
}

export interface GoPayAccountCreatePinStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
}

export interface GoPayAccountCreatePinCompleteRequest {
  gopay_account_id: string;
  otp: string;
  pin: string;
}

export interface GoPayAccountCreatePinCompleteResponse {
  success: boolean;
  error_message: string;
  phone: string;
  pin_setup_complete: boolean;
}

export interface GoPayAppStepInput {
  job_id: string;
  activation_id: string;
  state_json: string;
}

export interface GoPayAppStepOutput {
  activation_id: string;
  ready: boolean;
  stage: string;
  phone: string;
  account_token_ready: boolean;
  change_phone_complete: boolean;
  deactivate_complete: boolean;
  signup_complete: boolean;
  signup_pin_complete: boolean;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppChangePhoneStartInput {
  job_id: string;
  failure_count: number;
  state_json: string;
  activation_id: string;
  phone: string;
  pin: string;
  country_code: string;
}

export interface GoPayAppChangePhoneStartOutput {
  activation_id: string;
  phone: string;
  failure_count: number;
  max_failures: number;
  otp_timeout_seconds: number;
  otp_retry_attempts: number;
  data: { [key: string]: any } | undefined;
  state_json: string;
  retryable_failure: boolean;
  error_message: string;
}

export interface GoPayAppChangePhoneGetNumberInput {
  job_id: string;
  failure_count: number;
  account_id: string;
  gopay_account_id: string;
  country_code: string;
}

export interface GoPayAppChangePhoneGetNumberOutput {
  activation_id: string;
  phone: string;
  failure_count: number;
  max_failures: number;
  data: { [key: string]: any } | undefined;
}

export interface GoPayAppAcquireSignupPhoneInput {
  job_id: string;
  failure_count: number;
}

export interface GoPayAppAcquireSignupPhoneOutput {
  activation_id: string;
  phone: string;
  failure_count: number;
  max_failures: number;
  otp_timeout_seconds: number;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppGenerateDeviceProxyInput {
  job_id: string;
  account_id: string;
  country_code: string;
}

export interface GoPayAppGenerateDeviceProxyOutput {
  state_json: string;
  proxy_slot: number;
  dynamic_egress_size: number;
  proxy_hash: string;
  device_fingerprint: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayAppCheckSignupPhoneInput {
  job_id: string;
  activation_id: string;
  phone: string;
  country_code: string;
  state_json: string;
}

export interface GoPayAppCheckSignupPhoneOutput {
  activation_id: string;
  phone: string;
  status: string;
  available: boolean;
  state_json: string;
  proxy_slot: number;
  dynamic_egress_size: number;
  proxy_hash: string;
  device_fingerprint: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayResolveWAPhoneInput {
  job_id: string;
  gopay_account_id: string;
  wa_phone: string;
}

export interface GoPayResolveWAPhoneOutput {
  gopay_account_id: string;
  wa_phone: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayAppStateActivityInput {
  job_id: string;
  gopay_account_id: string;
  state_json: string;
  reason: string;
}

export interface GoPayAppStateActivityOutput {
  gopay_account_id: string;
  state_json: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayPaymentRebindSourceInput {
  job_id: string;
  source_job_id: string;
  account_id: string;
  gopay_account_id: string;
}

export interface GoPayPaymentRebindSourceOutput {
  source_job_id: string;
  account_id: string;
  gopay_account_id: string;
  wa_phone: string;
  charge_ref: string;
  snap_token: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayAppChangePhoneRetryInput {
  job_id: string;
  activation_id: string;
  otp_attempt: number;
  state_json: string;
}

export interface GoPayAppChangePhoneRetryOutput {
  activation_id: string;
  otp_sent: boolean;
  error_message: string;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppSMSActivationInput {
  job_id: string;
  activation_id: string;
  failure_count: number;
  reason: string;
}

export interface GoPayAppSMSActivationOutput {
  activation_id: string;
  failure_count: number;
  max_failures: number;
  error_message: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayAppChangePhoneCompleteInput {
  job_id: string;
  activation_id: string;
  code: string;
  failure_count: number;
  state_json: string;
  otp_param: string;
  submitted_at_param: string;
  issued_after_unix: number;
}

export interface GoPayAppChangePhoneCompleteOutput {
  activation_id: string;
  change_phone_complete: boolean;
  retryable_failure: boolean;
  failure_count: number;
  max_failures: number;
  error_message: string;
  stage: string;
  phone: string;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppDeactivateStartInput {
  job_id: string;
  activation_id: string;
  state_json: string;
  pin: string;
}

export interface GoPayAppDeactivateStartOutput {
  activation_id: string;
  otp_required: boolean;
  timeout_seconds: number;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppDeactivateCompleteInput {
  job_id: string;
  activation_id: string;
  code: string;
  state_json: string;
  otp_param: string;
  submitted_at_param: string;
  issued_after_unix: number;
}

export interface GoPayAppDeactivateCompleteOutput {
  activation_id: string;
  deactivate_complete: boolean;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppOTPStartInput {
  job_id: string;
  operation: string;
  step_name: string;
  phone: string;
  /** sms 或 wa；默认 sms */
  otp_channel: string;
  sms_activation_id: string;
  reset_state: boolean;
  state_json: string;
  pin: string;
  country_code: string;
  skip_phone_probe: boolean;
}

export interface GoPayAppCreatePinStartInput {
  job_id: string;
  /** sms 或 wa；默认 sms */
  otp_channel: string;
  sms_activation_id: string;
  state_json: string;
  data: { [key: string]: any } | undefined;
  pin: string;
}

export interface GoPayAppOTPOutput {
  operation: string;
  otp_required: boolean;
  issued_after_unix: number;
  timeout_seconds: number;
  ready: boolean;
  account_token_ready: boolean;
  signup_complete: boolean;
  signup_pin_complete: boolean;
  pin_setup_required: boolean;
  stage: string;
  phone: string;
  data: { [key: string]: any } | undefined;
  verification_method: string;
  otp_channel: string;
  state_json: string;
}

export interface GoPayAppCreatePinCompleteInput {
  job_id: string;
  otp_param: string;
  submitted_at_param: string;
  issued_after_unix: number;
  otp_source: string;
  data: { [key: string]: any } | undefined;
  otp_channel: string;
  sms_activation_id: string;
  state_json: string;
  pin: string;
}

export interface GoPayAppOTPCompleteInput {
  job_id: string;
  operation: string;
  otp_param: string;
  submitted_at_param: string;
  issued_after_unix: number;
  otp_source: string;
  data: { [key: string]: any } | undefined;
  otp_channel: string;
  sms_activation_id: string;
  state_json: string;
  pin: string;
}
