// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_otp.proto

/* eslint-disable */

export const protobufPackage = "orchestrator";

export interface SubmitOTPRequest {
  otp: string;
  channel: string;
  target: string;
}

export interface SubmitOTPResponse {
  success: boolean;
  job_id: string;
  error_message: string;
}

export interface ResendOTPRequest {
  job_id: string;
}

export interface ResendOTPResponse {
  success: boolean;
  job_id: string;
  error_message: string;
}
