// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_activity_data.proto

/* eslint-disable */

export const protobufPackage = "orchestrator";

export interface ActivityRegisterResultData {
  response_present?: boolean | undefined;
  success?: boolean | undefined;
  error_message: string;
  session_token_present?: boolean | undefined;
  access_token_present?: boolean | undefined;
  device_id_present?: boolean | undefined;
  plus_trial_eligible?: boolean | undefined;
  plus_trial_checked?: boolean | undefined;
  checkout_url_present?: boolean | undefined;
  sensitive_values_stored?: boolean | undefined;
  credential_values_stored?: boolean | undefined;
}

export interface ActivityBrowserStartData {
  response_present?: boolean | undefined;
  success?: boolean | undefined;
  error_message: string;
  browser_session_id: string;
  otp_required?: boolean | undefined;
  otp_issued_after: number;
  otp_wait_started_at_unix: number;
  otp_request_action_started_at_unix: number;
  stage: string;
  status_message: string;
  result: ActivityRegisterResultData | undefined;
}

export interface ActivityBrowserAuthStartStepData {
  account_id: string;
  email: string;
  browser_start: ActivityBrowserStartData | undefined;
  otp_kind: string;
  browser_complete: ActivityRegisterResultData | undefined;
  terminal_reason: string;
  mode: string;
}

export interface ActivityBrowserAuthCompleteStepData {
  account_id: string;
  browser_session_id: string;
  mode: string;
  otp_source: string;
  otp_kind: string;
  browser_complete: ActivityRegisterResultData | undefined;
  terminal_reason: string;
}

export interface ActivityRegisterOutputData {
  browser_auth_start: ActivityBrowserAuthStartStepData | undefined;
  browser_auth_complete: ActivityBrowserAuthCompleteStepData | undefined;
  protocol_auth: ActivityProtocolAuthStepData | undefined;
}

export interface ActivityBrowserResendOTPData {
  response_present?: boolean | undefined;
  success?: boolean | undefined;
  error_message: string;
  browser_session_id: string;
  email: string;
  otp_issued_after_unix: number;
  otp_request_started_at_unix_ms: number;
  mode: string;
}

export interface ActivityBrowserAuthOTPRequestStepData {
  account_id: string;
  browser_session_id: string;
  mode: string;
  otp_kind: string;
  browser_resend: ActivityBrowserResendOTPData | undefined;
  otp_issued_after_unix: number;
  otp_request_started_at_unix_ms: number;
  terminal_reason: string;
}

export interface ActivityProtocolAuthStepData {
  driver: string;
  mode: string;
  account_id: string;
  email: string;
  flow_id: string;
  login_stage: string;
  protocol_session_started?: boolean | undefined;
  email_otp_issued_after_unix: number;
  otp_source: string;
  chatgpt_signin_login_hint?: boolean | undefined;
  chatgpt_signin_screen_hint: string;
  chatgpt_auth_url_ready?: boolean | undefined;
  chatgpt_csrf_status: number;
  chatgpt_csrf_attempt: number;
  chatgpt_csrf_edge_challenge?: boolean | undefined;
  chatgpt_csrf_ready?: boolean | undefined;
  email_otp_send_error: string;
  email_otp_send_status: number;
  profile_name_present?: boolean | undefined;
  profile_birthdate_present?: boolean | undefined;
  callback_url_captured?: boolean | undefined;
  session_token_present?: boolean | undefined;
  access_token_present?: boolean | undefined;
  terminal_reason: string;
  sentinel_error: string;
  sentinel_flow: string;
  sentinel_token_present?: boolean | undefined;
  sentinel_t_present?: boolean | undefined;
  workspace_select_error: string;
  workspace_select_status: number;
  workspace_selected?: boolean | undefined;
  choose_account_error: string;
  choose_account_status: number;
  choose_account_selected?: boolean | undefined;
}

export interface ActivityProtocolProxyUseData {
  driver: string;
  account_id: string;
  mode: string;
  use_proxy?: boolean | undefined;
  protocol_proxy_requested_country: string;
  protocol_proxy_requested_region: string;
  protocol_proxy_requested_state: string;
  error_message: string;
  protocol_proxy_in_use?: boolean | undefined;
  protocol_proxy_url_source: string;
}

export interface ActivityProtocolAuthEdgeData {
  driver: string;
  mode: string;
  account_id: string;
  auth_edge_check_target: string;
  auth_edge_accepted?: boolean | undefined;
  error_message: string;
  chatgpt_csrf_status: number;
  chatgpt_csrf_attempt: number;
  chatgpt_csrf_edge_challenge?: boolean | undefined;
  chatgpt_csrf_ready?: boolean | undefined;
}

export interface ActivityProtocolAuthOutputData {
  protocol_auth: ActivityProtocolAuthStepData | undefined;
  protocol_proxy_use: ActivityProtocolProxyUseData | undefined;
  auth_edge: ActivityProtocolAuthEdgeData | undefined;
}

export interface ActivityCodexOAuthStepData {
  label: string;
  driver: string;
  profile_key: string;
  country_iso2: string;
  country_calling_code: string;
  max_reuse_count: number;
  verification_channel: string;
  phone_reused?: boolean | undefined;
  phone_reuse_count: number;
  phone_reuse_limit: number;
  phone_expires_at_unix: number;
  phone_activation_id: string;
  phone_country_iso2: string;
  phone_country_code: string;
  phone_mask: string;
  activation_id: string;
  released?: boolean | undefined;
  reason: string;
  error_message: string;
  flow_id: string;
  login_stage: string;
  protocol_session_started?: boolean | undefined;
  device_id_present?: boolean | undefined;
  pkce_secret_key: string;
  pkce_secret_written?: boolean | undefined;
  browser_session_started?: boolean | undefined;
  auth_secret_key: string;
  auth_secret_written?: boolean | undefined;
  account_auth_written?: boolean | undefined;
  callback_url_captured?: boolean | undefined;
  account_phone_status: string;
  account_phone_need_written?: boolean | undefined;
  account_phone_confirmed_written?: boolean | undefined;
  account_phone_need_write_error: string;
  add_phone_required?: boolean | undefined;
  add_phone_confirmed?: boolean | undefined;
  add_phone_pending_stage: string;
  add_phone_required_source: string;
  email_otp_issued_after_unix: number;
  phone_otp_issued_after_unix: number;
  phone_otp_resend_issued_after_unix: number;
  phone_otp_received?: boolean | undefined;
  phone_validity_confirmed?: boolean | undefined;
  phone_validity_failure: string;
  phone_resend_click_error: string;
  sms_request_additional_error: string;
  sms_mark_sent_error: string;
  sms_first_wait_error: string;
  sms_resend_request_error: string;
  post_add_phone_stage: string;
  client_auth_session_dump_error: string;
  client_auth_session_dump_status: number;
  client_auth_session_dump_seen?: boolean | undefined;
  client_auth_session_keys: string[];
  client_auth_openai_client_id_present?: boolean | undefined;
  client_auth_session_id_present?: boolean | undefined;
  client_auth_email_verification_mode: string;
  client_auth_email_verified?: boolean | undefined;
  client_auth_phone_state_known?: boolean | undefined;
  client_auth_phone_present?: boolean | undefined;
  client_auth_phone_status: string;
  client_auth_phone_verification_channel: string;
  client_auth_phone_mask: string;
  sentinel_error: string;
  sentinel_flow: string;
  sentinel_token_present?: boolean | undefined;
  sentinel_t_present?: boolean | undefined;
  workspace_select_error: string;
  workspace_select_status: number;
  workspace_selected?: boolean | undefined;
  choose_account_error: string;
  choose_account_status: number;
  choose_account_selected?: boolean | undefined;
  account_id: string;
  n8n_execution_id: string;
}

export interface ActivityProgressSnapshotData {
  message: string;
  at_unix: number;
  fields: ActivityProgressFields | undefined;
}

export interface ActivityProgressFields {
  browser_auth_start: ActivityBrowserAuthStartStepData | undefined;
  browser_auth_complete: ActivityBrowserAuthCompleteStepData | undefined;
  browser_auth_otp_request: ActivityBrowserAuthOTPRequestStepData | undefined;
  protocol_auth: ActivityProtocolAuthStepData | undefined;
  protocol_proxy_use: ActivityProtocolProxyUseData | undefined;
  protocol_auth_edge: ActivityProtocolAuthEdgeData | undefined;
  codex_oauth: ActivityCodexOAuthStepData | undefined;
  probe_plus_trial: ActivityProbePlusTrialStepData | undefined;
  probe_tier: ActivityProbeTierStepData | undefined;
}

export interface ActivityProgressData {
  progress_message: string;
  progress_at_unix: number;
  progress: ActivityProgressSnapshotData | undefined;
}

export interface ActivityProbePlusTrialData {
  response_present?: boolean | undefined;
  success?: boolean | undefined;
  error_message: string;
  checked?: boolean | undefined;
  plus_trial_eligible?: boolean | undefined;
  plus_active?: boolean | undefined;
  plan_type: string;
  tier: string;
  amount: number;
  currency: string;
  source: string;
  checkout_url_present?: boolean | undefined;
  checkout_session_id: string;
}

export interface ActivityProbeTierData {
  response_present?: boolean | undefined;
  success?: boolean | undefined;
  error_message: string;
  checked?: boolean | undefined;
  tier: string;
  plus_active?: boolean | undefined;
  source: string;
}

export interface ActivityProbePlusTrialStepData {
  account_id: string;
  session_token_present?: boolean | undefined;
  access_token_present?: boolean | undefined;
  credential_kind: string;
  payment_probe: ActivityProbePlusTrialData | undefined;
  success?: boolean | undefined;
  checked?: boolean | undefined;
  plus_trial_eligible?: boolean | undefined;
  plus_active?: boolean | undefined;
  plan_type: string;
  tier: string;
  amount: number;
  currency: string;
  source: string;
  checkout_url_present?: boolean | undefined;
  checkout_session_id: string;
  error_message: string;
}

export interface ActivityProbeTierStepData {
  account_id: string;
  session_token_present?: boolean | undefined;
  access_token_present?: boolean | undefined;
  credential_kind: string;
  tier_probe: ActivityProbeTierData | undefined;
  success?: boolean | undefined;
  checked?: boolean | undefined;
  tier: string;
  plus_active?: boolean | undefined;
  source: string;
  error_message: string;
}
