// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_settings.proto

/* eslint-disable */

export const protobufPackage = "orchestrator";

export enum GPTPluginConfigFieldKind {
  GPT_PLUGIN_CONFIG_FIELD_KIND_UNSPECIFIED = "GPT_PLUGIN_CONFIG_FIELD_KIND_UNSPECIFIED",
  GPT_PLUGIN_CONFIG_FIELD_KIND_STRING = "GPT_PLUGIN_CONFIG_FIELD_KIND_STRING",
  GPT_PLUGIN_CONFIG_FIELD_KIND_SECRET = "GPT_PLUGIN_CONFIG_FIELD_KIND_SECRET",
  GPT_PLUGIN_CONFIG_FIELD_KIND_INTEGER = "GPT_PLUGIN_CONFIG_FIELD_KIND_INTEGER",
  GPT_PLUGIN_CONFIG_FIELD_KIND_BOOLEAN = "GPT_PLUGIN_CONFIG_FIELD_KIND_BOOLEAN",
  GPT_PLUGIN_CONFIG_FIELD_KIND_DURATION_SECONDS = "GPT_PLUGIN_CONFIG_FIELD_KIND_DURATION_SECONDS",
  GPT_PLUGIN_CONFIG_FIELD_KIND_URL = "GPT_PLUGIN_CONFIG_FIELD_KIND_URL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface GPTProxyPreflightSettings {
  enabled: boolean;
  require_residential?: boolean | undefined;
  min_ip_purity_score: number;
  cf_canary_enabled?: boolean | undefined;
  max_proxy_attempts: number;
  target_connectivity_urls: string[];
}

export interface GPTPluginConfigField {
  key: string;
  label: string;
  kind: GPTPluginConfigFieldKind;
  default_value: string;
  required: boolean;
  help_text: string;
}

export interface GPTPluginConfigSchema {
  plugin_key: string;
  display_name: string;
  owner: string;
  fields: GPTPluginConfigField[];
}

export interface GPTPluginConfig {
  plugin_key: string;
  values: { [key: string]: string };
}

export interface GPTPluginConfig_ValuesEntry {
  key: string;
  value: string;
}

export interface GPTSettings {
  proxy_preflight: GPTProxyPreflightSettings | undefined;
  plugin_configs: GPTPluginConfig[];
}

export interface GetGPTSettingsResponse {
  settings: GPTSettings | undefined;
  error_message: string;
  plugin_schemas: GPTPluginConfigSchema[];
}

export interface UpdateGPTSettingsRequest {
  settings: GPTSettings | undefined;
}

export interface UpdateGPTSettingsResponse {
  settings: GPTSettings | undefined;
  error_message: string;
}
