// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_job.proto

/* eslint-disable */
import type {
  ActivityBrowserAuthCompleteStepData,
  ActivityBrowserAuthOTPRequestStepData,
  ActivityBrowserAuthStartStepData,
  ActivityCodexOAuthStepData,
  ActivityProbePlusTrialStepData,
  ActivityProbeTierStepData,
  ActivityProgressData,
  ActivityProtocolAuthEdgeData,
  ActivityProtocolAuthStepData,
  ActivityProtocolProxyUseData,
} from "./orchestrator_activity_data";
import type {
  N8NAuthFailureData,
  N8NAuthFinishData,
  N8NChannelOTPCompleteData,
  N8NChannelOTPWaitDetail,
  N8NCodexOAuthBatchCompleteData,
  N8NDynamicProxyGeoData,
  N8NDynamicProxyPreflightData,
  N8NDynamicProxyPreflightDetail,
  N8NProbeCompleteData,
  N8NProbeTokenData,
} from "./orchestrator_n8n";

export const protobufPackage = "orchestrator";

export enum GPTActionEngine {
  GPT_ACTION_ENGINE_UNSPECIFIED = "GPT_ACTION_ENGINE_UNSPECIFIED",
  GPT_ACTION_ENGINE_N8N = "GPT_ACTION_ENGINE_N8N",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface GPTActionButton {
  id: string;
  label: string;
  placement: string;
  intent: string;
  start_path: string;
}

export interface GPTWorkflowDefinition {
  key: string;
  start_path: string;
  n8n_action_scope: string;
  n8n_webhook_path: string;
  action_path_prefix: string;
}

export interface GPTActionDefinition {
  action_id: string;
  display_name: string;
  owner: string;
  engine: GPTActionEngine;
  request_proto: string;
  response_proto: string;
  required_account_statuses: string[];
  required_fields: string[];
  capabilities: string[];
  visibility: string;
  workflow: GPTWorkflowDefinition | undefined;
  ui_buttons: GPTActionButton[];
  blocked_account_statuses: string[];
}

export interface GPTActionCatalogResponse {
  actions: GPTActionDefinition[];
}

export interface CreateJobInput {
  job_id: string;
  account_id: string;
  action: string;
  params: { [key: string]: string };
}

export interface CreateJobInput_ParamsEntry {
  key: string;
  value: string;
}

export interface JobStepStartInput {
  job_id: string;
  step_name: string;
  recoverable: boolean;
  retryable: boolean;
  detail: JobData | undefined;
}

export interface JobStepCompleteInput {
  job_id: string;
  step_name: string;
  recoverable: boolean;
  retryable: boolean;
  result: JobData | undefined;
}

export interface ResolveAccountInput {
  account_id: string;
  source_job_id: string;
}

export interface JobFailureInput {
  job_id: string;
  step_name: string;
  status: string;
  recoverable: boolean;
  retryable: boolean;
  error_message: string;
  result: JobData | undefined;
}

export interface JobSuccessInput {
  job_id: string;
  result: JobData | undefined;
}

export interface JobStep {
  step_name: string;
  status: string;
  recoverable: boolean;
  retryable: boolean;
  error_message: string;
  detail: JobData | undefined;
  started_at: number;
  completed_at: number;
}

export interface Job {
  job_id: string;
  account_id: string;
  action: string;
  status: string;
  recoverable: boolean;
  retryable: boolean;
  last_step: string;
  error_message: string;
  result: JobData | undefined;
  created_at: number;
  updated_at: number;
  steps: JobStep[];
  n8n_execution_id: string;
}

export interface WorkflowProgress {
  job_id: string;
  workflow: string;
  step_name: string;
  status: string;
  error_message: string;
  updated_at_unix: number;
}

export interface JobSnapshot {
  job: Job | undefined;
  progress: WorkflowProgress | undefined;
  event_id: number;
}

export interface JobEvent {
  event_id: number;
  job_id: string;
  event_type: string;
  snapshot: JobSnapshot | undefined;
}

export interface GetJobRequest {
  job_id: string;
}

export interface GetJobResponse {
  snapshot: JobSnapshot | undefined;
  error_message: string;
}

export interface ListJobsRequest {
  limit: number;
  status: string;
  action: string;
  account_id: string;
  before: JobListCursor | undefined;
}

export interface ListJobsResponse {
  snapshots: JobSnapshot[];
  error_message: string;
  next: JobListCursor | undefined;
  has_more: boolean;
}

export interface JobListCursor {
  updated_at: number;
  job_id: string;
}

export interface CancelJobRequest {
  job_id: string;
  reason: string;
}

export interface JobData {
  cancel: JobCancelResultData | undefined;
  channel_otp_wait: N8NChannelOTPWaitDetail | undefined;
  channel_otp_complete: N8NChannelOTPCompleteData | undefined;
  dynamic_proxy_preflight_detail: N8NDynamicProxyPreflightDetail | undefined;
  dynamic_proxy_preflight: N8NDynamicProxyPreflightData | undefined;
  dynamic_proxy_geo: N8NDynamicProxyGeoData | undefined;
  auth_finish: N8NAuthFinishData | undefined;
  auth_failure: N8NAuthFailureData | undefined;
  codex_oauth: ActivityCodexOAuthStepData | undefined;
  codex_oauth_batch: N8NCodexOAuthBatchCompleteData | undefined;
  probe_complete: N8NProbeCompleteData | undefined;
  probe_token: N8NProbeTokenData | undefined;
  probe_plus_trial: ActivityProbePlusTrialStepData | undefined;
  probe_tier: ActivityProbeTierStepData | undefined;
  activity_progress: ActivityProgressData | undefined;
  browser_auth_start: ActivityBrowserAuthStartStepData | undefined;
  browser_auth_complete: ActivityBrowserAuthCompleteStepData | undefined;
  browser_auth_otp_request: ActivityBrowserAuthOTPRequestStepData | undefined;
  protocol_auth: ActivityProtocolAuthStepData | undefined;
  protocol_proxy_use: ActivityProtocolProxyUseData | undefined;
  protocol_auth_edge: ActivityProtocolAuthEdgeData | undefined;
}

export interface JobCancelResultData {
  canceled: boolean;
  reason: string;
  engine: string;
}

export interface CancelJobResponse {
  success: boolean;
  job_id: string;
  snapshot: JobSnapshot | undefined;
  error_message: string;
}
