// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_account.proto

/* eslint-disable */
import type { Account as Account1 } from "@byte-v-forge/common-ui/proto/byte/v/forge/contracts/account/v1/account";
import type { FetchMailboxInboxesResponse } from "@byte-v-forge/common-ui/proto/byte/v/forge/contracts/mailbox/v1/mailbox";
import type {
  ProxyChainPlan,
  ProxyEdgeAccessCheck,
  ProxyIPFraudCheck,
} from "./byte/v/forge/contracts/proxyruntime/v1/proxy_runtime";
import type { Account } from "./gpt_account";
import type {
  ActivityBrowserAuthOTPRequestStepData,
  ActivityBrowserAuthStartStepData,
  ActivityCodexOAuthStepData,
  ActivityProtocolAuthOutputData,
  ActivityProtocolAuthStepData,
  ActivityRegisterOutputData,
} from "./orchestrator_activity_data";

export const protobufPackage = "orchestrator";

export enum AccountEmailStrategy {
  ACCOUNT_EMAIL_STRATEGY_UNSPECIFIED = "ACCOUNT_EMAIL_STRATEGY_UNSPECIFIED",
  ACCOUNT_EMAIL_STRATEGY_EXPLICIT = "ACCOUNT_EMAIL_STRATEGY_EXPLICIT",
  ACCOUNT_EMAIL_STRATEGY_POOLED_PRIMARY = "ACCOUNT_EMAIL_STRATEGY_POOLED_PRIMARY",
  ACCOUNT_EMAIL_STRATEGY_POOLED_ALIAS = "ACCOUNT_EMAIL_STRATEGY_POOLED_ALIAS",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum RegisterOTPMode {
  REGISTER_OTP_MODE_UNSPECIFIED = "REGISTER_OTP_MODE_UNSPECIFIED",
  REGISTER_OTP_MODE_AUTO = "REGISTER_OTP_MODE_AUTO",
  REGISTER_OTP_MODE_MANUAL = "REGISTER_OTP_MODE_MANUAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface RegisterOTPOptions {
  mode: RegisterOTPMode;
  auto_resend?: boolean | undefined;
  first_wait_seconds: number;
  timeout_seconds: number;
}

export interface AccountSpec {
  account_id: string;
  email: string;
  password: string;
  email_strategy: AccountEmailStrategy;
  country_code: string;
  region: string;
}

export interface AccountRef {
  account_id: string;
  plus_trial_known: boolean;
  plus_trial_eligible: boolean;
  plus_active: boolean;
  tier: string;
}

export interface EnsureAccountInput {
  account: AccountSpec | undefined;
}

export interface CreateGPTAccountRequest {
  email: string;
  password: string;
  account_id: string;
  email_strategy: AccountEmailStrategy;
  country_code: string;
  region: string;
}

export interface CreateGPTAccountResponse {
  account: Account | undefined;
  error_message: string;
}

export interface FetchAccountMailboxRequest {
  account_id: string;
  limit_per_mailbox: number;
}

export interface FetchAccountMailboxResponse {
  account: Account | undefined;
  inbox: FetchMailboxInboxesResponse | undefined;
  error_message: string;
}

export interface AccountFingerprintRequest {
  account_id: string;
  country_code: string;
  region: string;
}

export interface AccountFingerprintResponse {
  account_id: string;
  generated: boolean;
  country_code: string;
  region: string;
  browser_profile_template: string;
  browser_family: string;
  browser_major_version: string;
  os_family: string;
  tls_profile_family: string;
  tls_fingerprint_variant: string;
  locale: string;
  timezone: string;
  user_agent: string;
  accept_language: string;
  language: string;
  device_id: string;
  created_at: number;
  updated_at: number;
}

export interface UpdateAccountAuthRequest {
  session_token: string;
  access_token: string;
  activation_channel?: string | undefined;
}

export interface AccountAuthResponse {
  session_token: string;
  session_token_expires_at_unix: number;
  access_token: string;
  access_token_expires_at_unix: number;
  account: Account1 | undefined;
}

export interface AccountProxyUsage {
  id: string;
  account_id: string;
  job_id: string;
  n8n_execution_id: string;
  purpose: string;
  proxy_url_hash: string;
  session_id_hash: string;
  exit_ip: string;
  country_code: string;
  region: string;
  city: string;
  ip_fraud_check: ProxyIPFraudCheck | undefined;
  edge_access_check: ProxyEdgeAccessCheck | undefined;
  target_reachable: boolean;
  attempt_index: number;
  accepted: boolean;
  error_message: string;
  created_at: number;
  chain: ProxyChainPlan | undefined;
}

export interface ListAccountProxyUsagesResponse {
  usages: AccountProxyUsage[];
}

export interface PersistRegisteredInput {
  account_id: string;
  session_token: string;
  access_token: string;
  plus_trial_eligible: boolean;
  plus_trial_checked: boolean;
}

export interface RegisterActivityOutput {
  session_token: string;
  access_token: string;
  device_id: string;
  plus_trial_eligible: boolean;
  plus_trial_checked: boolean;
  checkout_url: string;
  data: ActivityRegisterOutputData | undefined;
}

export interface BrowserAuthStartInput {
  job_id: string;
  account_id: string;
  mode: string;
}

export interface BrowserAuthStartOutput {
  account_id: string;
  browser_session_id: string;
  email: string;
  otp_required: boolean;
  otp_issued_after_unix: number;
  otp_timeout_seconds: number;
  result: RegisterActivityOutput | undefined;
  data: ActivityBrowserAuthStartStepData | undefined;
  otp_wait_started_at_unix: number;
  otp_request_action_started_at_unix: number;
}

export interface ProtocolAuthStartInput {
  job_id: string;
  account_id: string;
  mode: string;
  country_code: string;
  region: string;
  proxy_url: string;
}

export interface ProtocolAuthStartOutput {
  account_id: string;
  flow_id: string;
  email: string;
  otp_required: boolean;
  otp_issued_after_unix: number;
  otp_timeout_seconds: number;
  result: RegisterActivityOutput | undefined;
  data: ActivityProtocolAuthOutputData | undefined;
  otp_wait_started_at_unix: number;
  otp_request_action_started_at_unix: number;
}

export interface BrowserAuthCompleteInput {
  job_id: string;
  account_id: string;
  browser_session_id: string;
  mode: string;
  otp_param: string;
  submitted_at_param: string;
  otp_issued_after_unix: number;
  otp_source: string;
}

export interface BrowserAuthResendOTPInput {
  job_id: string;
  account_id: string;
  browser_session_id: string;
  mode: string;
}

export interface BrowserAuthResendOTPOutput {
  browser_session_id: string;
  email: string;
  success: boolean;
  error_message: string;
  otp_issued_after_unix: number;
  otp_request_started_at_unix_ms: number;
  otp_timeout_seconds: number;
  data: ActivityBrowserAuthOTPRequestStepData | undefined;
}

export interface ProtocolAuthWaitInput {
  job_id: string;
  account_id: string;
  flow_id: string;
  mode: string;
  email: string;
  proxy_url: string;
}

export interface ProtocolAuthWaitOutput {
  account_id: string;
  flow_id: string;
  email: string;
  otp_required: boolean;
  otp_issued_after_unix: number;
  otp_timeout_seconds: number;
  result: RegisterActivityOutput | undefined;
  data: ActivityProtocolAuthStepData | undefined;
  otp_wait_started_at_unix: number;
  otp_request_action_started_at_unix: number;
}

export interface ProtocolAuthCompleteInput {
  job_id: string;
  account_id: string;
  flow_id: string;
  mode: string;
  otp_param: string;
  submitted_at_param: string;
  otp_issued_after_unix: number;
  otp_source: string;
  proxy_url: string;
}

export interface ProtocolAuthCancelInput {
  flow_id: string;
  mode: string;
  job_id: string;
}

export interface BrowserAuthCancelInput {
  browser_session_id: string;
  mode: string;
  job_id: string;
}

export interface RegisterAccountRequest {
  email: string;
  password: string;
  account_id: string;
  email_strategy: AccountEmailStrategy;
  otp_options: RegisterOTPOptions | undefined;
  country_code: string;
  region: string;
}

export interface RegisterAccountResponse {
  job_id: string;
  session_token: string;
  plus_trial_eligible: boolean;
  error_message: string;
  checkout_url: string;
  access_token: string;
  started: boolean;
}

export interface LoginAccountRequest {
  account_id: string;
}

export interface LoginAccountResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}

export interface CodexOAuthRequest {
  account_id: string;
  label: string;
}

export interface CodexOAuthResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}

export interface CodexOAuthAddPhoneRequest {
  account_id: string;
  label: string;
  max_reuse_count: number;
}

export interface CodexOAuthAddPhoneResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}

export interface CodexOAuthBatchAddPhoneRequest {
  account_ids: string[];
  label: string;
  max_reuse_count: number;
}

export interface CodexOAuthBatchAddPhoneResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}

export interface CodexOAuthAcquirePhoneInput {
  job_id: string;
  account_id: string;
  label: string;
  max_reuse_count: number;
}

export interface CodexOAuthPhoneLease {
  activation_id: string;
  phone_e164: string;
  phone_national: string;
  country_iso2: string;
  country_calling_code: string;
  label: string;
  reuse_count: number;
  reuse_limit: number;
  reused: boolean;
  profile_key: string;
  expires_at_unix: number;
}

export interface CodexOAuthBrowserSession {
  flow_id: string;
  session_id: string;
  state: string;
  pkce_secret_key: string;
}

export interface CodexOAuthStartBrowserInput {
  job_id: string;
  account_id: string;
  label: string;
  phone: CodexOAuthPhoneLease | undefined;
  allow_add_phone: boolean;
}

export interface CodexOAuthStartBrowserOutput {
  success: boolean;
  error_message: string;
  session: CodexOAuthBrowserSession | undefined;
  data: ActivityCodexOAuthStepData | undefined;
  phone_label: string;
}

export interface CodexOAuthBrowserStepInput {
  job_id: string;
  account_id: string;
  label: string;
  session: CodexOAuthBrowserSession | undefined;
}

export interface CodexOAuthSubmitEmailOTPInput {
  job_id: string;
  account_id: string;
  label: string;
  session: CodexOAuthBrowserSession | undefined;
  issued_after_unix: number;
}

export interface CodexOAuthBrowserStageOutput {
  success: boolean;
  error_message: string;
  data: ActivityCodexOAuthStepData | undefined;
  stage: string;
  email_otp_issued_after_unix: number;
}

export interface CodexOAuthAddPhoneBrowserInput {
  job_id: string;
  account_id: string;
  label: string;
  phone: CodexOAuthPhoneLease | undefined;
  allow_add_phone: boolean;
  session: CodexOAuthBrowserSession | undefined;
}

export interface CodexOAuthAddPhoneBrowserOutput {
  success: boolean;
  error_message: string;
  data: ActivityCodexOAuthStepData | undefined;
  add_phone_confirmed: boolean;
  add_phone_required: boolean;
  phone_reuse_count: number;
  phone_reuse_limit: number;
}

export interface CodexOAuthCompleteBrowserInput {
  job_id: string;
  account_id: string;
  label: string;
  mark_phone_confirmed_on_success: boolean;
  session: CodexOAuthBrowserSession | undefined;
}

export interface CodexOAuthCompleteBrowserOutput {
  success: boolean;
  error_message: string;
  auth_secret_key: string;
  data: ActivityCodexOAuthStepData | undefined;
}

export interface CodexOAuthStopBrowserInput {
  job_id: string;
  session: CodexOAuthBrowserSession | undefined;
  reason: string;
}

export interface CodexOAuthReleasePhoneInput {
  job_id: string;
  account_id: string;
  activation_id: string;
  label: string;
  error_message: string;
}
