// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_payment.proto

/* eslint-disable */
import type { ActivityProbePlusTrialStepData, ActivityProbeTierStepData } from "./orchestrator_activity_data";

export const protobufPackage = "orchestrator";

export interface ProbePlusTrialActivityInput {
  job_id: string;
  account_id: string;
  access_token: string;
  session_token: string;
  proxy_url: string;
}

export interface ProbeTierActivityInput {
  job_id: string;
  account_id: string;
  proxy_url: string;
}

export interface ProbePlusTrialActivityOutput {
  success: boolean;
  checked: boolean;
  plus_trial_eligible: boolean;
  plus_active: boolean;
  amount: number;
  currency: string;
  source: string;
  plan_type: string;
  checkout_url: string;
  checkout_session_id: string;
  error_message: string;
  data: ActivityProbePlusTrialStepData | undefined;
}

export interface ProbeTierActivityOutput {
  success: boolean;
  checked: boolean;
  tier: string;
  plus_active: boolean;
  source: string;
  error_message: string;
  data: ActivityProbeTierStepData | undefined;
}

export interface ProbeAccountRequest {
  account_id: string;
}

export interface ProbeAccountResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}
