// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: payment.proto

/* eslint-disable */

export const protobufPackage = "payment";

export interface ChatGPTCredential {
  session_token: string;
  access_token: string;
  request_profile: ChatGPTRequestProfile | undefined;
}

export interface ChatGPTRequestProfile {
  proxy_url: string;
  tls_profile: string;
  user_agent: string;
  sec_ch_ua: string;
  sec_ch_ua_platform: string;
  accept_language: string;
  oai_language: string;
  locale: string;
  device_id: string;
  platform: string;
  proxy_ref: string;
  timezone: string;
}

export interface ProbePlusTrialPaymentRequest {
  credential: ChatGPTCredential | undefined;
}

export interface ProbePlusTrialPaymentResponse {
  success: boolean;
  error_message: string;
  checked: boolean;
  plus_trial_eligible: boolean;
  amount: number;
  currency: string;
  source: string;
  checkout_url: string;
  plus_active: boolean;
  plan_type: string;
  checkout_session_id: string;
}

export interface CreateCheckoutLinkRequest {
  credential: ChatGPTCredential | undefined;
}

export interface CreateCheckoutLinkResponse {
  success: boolean;
  error_message: string;
  checkout_url: string;
  checkout_session_id: string;
}

export interface ProbeTierPaymentRequest {
  credential: ChatGPTCredential | undefined;
}

export interface FetchAccessTokenPaymentRequest {
  credential: ChatGPTCredential | undefined;
}

export interface FetchAccessTokenPaymentResponse {
  success: boolean;
  error_message: string;
  access_token: string;
}

export interface ProbeTierPaymentResponse {
  success: boolean;
  error_message: string;
  checked: boolean;
  tier: string;
  plus_active: boolean;
  source: string;
}
